const WordPhraseResultData = [
  {
    title: "conference",
    subtitle: '会議',
    vocabulary: true,
    listening: true,
    speaking: true,
    writing: true,
  },
  {
    title: 'agenda',
    subtitle: '協議事項',
    vocabulary: true,
    listening: true,
    speaking: true,
    writing: true,
  },
  {
    title: 'objective',
    subtitle: '目的',
    vocabulary: true,
    listening: true,
    speaking: false,
    writing: true,
  },
  {
    title: 'Employment',
    subtitle: '雇用',
    vocabulary: true,
    listening: true,
    speaking: false,
    writing: false,
  },
  {
    title: 'Term',
    subtitle: '期間',
    vocabulary: true,
    listening: false,
    speaking: false,
    writing: true,
  },
  {
    title: 'Term of Employment',
    subtitle: '契約期間',
    vocabulary: true,
    listening: false,
    speaking: false,
    writing: false,
  },
  {
    title: 'Please refer to the attachment.',
    subtitle: '添付のファイルをご参照ください。',
    vocabulary: false,
    listening: false,
    speaking: false,
    writing: false,
  },
  {
    title: 'We have no choice but 〜',
    subtitle: '添付のファイルをご参照ください。',
    vocabulary: false,
    listening: false,
    speaking: false,
    writing: false,
  },
]

export default WordPhraseResultData;
